FROM python:3.10-slim


RUN mkdir /app \
    && apt-get update

COPY . /app

WORKDIR /app

RUN pip install --upgrade pip \
    && pip install -r requirements.txt

EXPOSE 8501:8501

CMD ["bash", "-c", \
    "streamlit run streamlit.py --server.port 8501"]